version: "3.9"

services:
  locust:
    build:
      context: ./locust
      dockerfile: Dockerfile
    container_name: locust
    depends_on:
      - backend
    user: "0:0"
    ports:
      - "8089:8089"
    command: >
      -f /mnt/locust/load_test.py
      --host http://backend:8000

  db:
    image: postgres:15
    container_name: watch_db
    restart: always
    environment:
      POSTGRES_USER: login
      POSTGRES_PASSWORD: password
      POSTGRES_DB: watch_cinema
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: watch_backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://login:password@db:5432/watch_cinema
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: watch_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  pgdata:
